{ ... }: {
  flake.modules.homeManager.email =
    {
      pkgs,
      config,
      lib,
      ...
    }:
    let
      calendars = {
        appointments = "042e3a44-5690-885d-a1de-925c02d808a2";
        assignments = "c6d5b965-4766-ce87-4f57-69231c579caa";
        personal = "fb021de2-8ab6-b841-915b-7fad234145ae";
        work = "80266e6b-eaed-52f4-2d5d-c2d7e2b98b74";
      };

      caldavConfig = uuid: ''
        			[General]
        			Binary = ${pkgs.calcurse}/bin/calcurse
        			Hostname = radicale.hp
        			Path = /sona/${uuid}/
        			HTTPS = No
        			DryRun = No

        			[Auth]
        			Username = sona
        			PasswordCommand = ${pkgs.pass}/bin/pass show radicale/password
        		'';

      syncScript = pkgs.writeShellScript "calcurse-sync-all" (
        lib.concatStringsSep "\n" (
          lib.mapAttrsToList (name: uuid: ''
            				${pkgs.calcurse}/bin/calcurse-caldav \
            					--config  ${config.xdg.configHome}/calcurse/caldav/${name}/config \
            					--syncdb  ${config.xdg.dataHome}/calcurse/caldav/${name}/sync.db \
            					--lockfile ${config.xdg.dataHome}/calcurse/caldav/${name}/lock
            			'') calendars
        )
      );
    in
    {
      home.packages = with pkgs; [
        calcurse
        protonmail-export
        protonmail-bridge
        protonmail-bridge-gui # needed for initial login
        protonmail-desktop
        thunderbird
        elinks
      ];

      programs.aerc = {
        enable = true;

        extraConfig = {
          general = {
            unsafe-accounts-conf = true;
            pgp-provider = "gpg";
          };
          compose.editor = "nvim";

          # Generated by Home Manager.
          viewer = {
            "pager" =
              "pager = bat --nonprintable-notation unicode --plain --tabs 4 --style numbers --force-colorization --paging always --squeeze-blank";
            "alternatives" = "text/plain,text/html";
          };

          filters = {
            "text/plain" = "colorize";
            "text/html" = "elinks -dump -dump-color-mode 1 -dump-width 80 -no-numbering -no-references";
          };
          ui.styleset-name = "dracula";
        };

        extraAccounts."Personal" = {
          source = "imap+insecure://sona%40stau.space@127.0.0.1:1143";
          outgoing = "smtp+insecure://sona%40stau.space@127.0.0.1:1025";
          default = "INBOX";
          from = "Sona Tau Estrada Rivera <sona@stau.space>";
          copy-to = "Sent";
          cache-headers = true;
          source-cred-cmd = "pass show proton/bridge-password";
          outgoing-cred-cmd = "pass show proton/bridge-password";
        };
      };

      # Calendars synced from Radicale on hp (accessible via Tailscale).
      # Phone → Radicale ← calcurse-caldav ← calcurse
      xdg.configFile =
        lib.mapAttrs' (
          name: uuid: lib.nameValuePair "calcurse/caldav/${name}/config" { text = caldavConfig uuid; }
        ) calendars
        // {
          "calcurse/hooks/pre-load" = {
            executable = true;
            text = ''
              					#!${pkgs.bash}/bin/bash
              					TODO="${config.xdg.dataHome}/calcurse/todo"
              					${pkgs.taskwarrior3}/bin/task export status:pending ready 2>/dev/null \
              						| ${pkgs.jq}/bin/jq -r '.[] |
              							( if .priority == "H" then 1
              							  elif .priority == "M" then 5
              							  elif .priority == "L" then 9
              							  else 0 end | tostring) as $p |
              							"[" + $p + "]" + .description' \
              						> "$TODO"
              				'';
          };
        };

      systemd.user.services.calcurse-caldav = {
        Unit.Description = "Sync calcurse calendars via CalDAV";
        Service = {
          Type = "oneshot";
          ExecStart = "${syncScript}";
          Environment = [
            "PATH=${
              lib.makeBinPath [
                pkgs.pass
                pkgs.gnupg
              ]
            }"
          ];
        };
      };

      systemd.user.timers.calcurse-caldav = {
        Unit.Description = "Periodic calcurse CalDAV sync";
        Timer = {
          OnCalendar = "*:0/15";
          Persistent = true;
        };
        Install.WantedBy = [ "timers.target" ];
      };

    };
}
