keys:
  # Machine host keys (derived from age -C age-keygen)
  - &hp   age1ujdlljqpna9e8tmk4ymns6mm6gnq8ac892mn4tuljsgnkzdt7y7qsru9h4
  - &fw13 age1rxvhxas7hu4dn6x6vywxdacd8ykzjxlvtufqzh232mvluf30kc8qka4rth
  - &est age1dx6jju76dzg0tphzk5a544vr8rd4z8aenj6gy2hrvjhf0nahh9kq3m97c5

  # User key (derived from ~/.ssh/id_ed25519)
  - &sona age12yh3lms50k0a5jdwmy9r5wuel8h947sd2asgul9al6666wkeevzqgrutnu

creation_rules:
  # hp-specific secrets: decryptable by hp host key and by sona's key
  - path_regex: secrets/hp\.yaml$
    key_groups:
      - age:
          - *hp
          - *sona
  - path_regex: secrets/attic\.yaml$
    key_groups:
      - age:
          - *hp
          - *fw13
          - *est

  # Shared secrets (e.g. cross-machine keys): sona's key only
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *sona
