# Generated by 'nixos-generate-config' on the hp machine.
{ config, lib, modulesPath, ... }: {
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot = {
		initrd = {
			availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
			kernelModules = [ ];
		};
		kernelModules = [ "kvm-intel" "sr_mod" "sg" "zfs" ];
		extraModulePackages = [ ];
	};

	fileSystems = {
		"/" = {
			device = "/dev/disk/by-uuid/4dea4b82-668b-499a-bb55-66057524fc97";
			fsType = "ext4";
		};
		"/boot" = {
			device = "/dev/disk/by-uuid/894E-13EB";
			fsType = "vfat";
			options = [ "fmask=0077" "dmask=0077" ];
		};
		"/storage" = {
			device = "storage/root";
			fsType = "zfs";
		};
	};

	swapDevices = [
		{ device = "/dev/disk/by-uuid/8a1bd975-3551-4f30-8332-afaf0d054338"; }
	];

	networking.useDHCP = lib.mkDefault true;
	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
