# Generated by 'nixos-generate-config'. Replace with actual hardware config.
# Run: nixos-generate-config --show-hardware-config > machine/est/description.nix
{ config, lib, pkgs, modulesPath, ... }: {
	imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

	boot = {
		initrd.kernelModules = [ ];
		kernelModules = [ "kvm-amd" ];
		extraModulePackages = [ ];

		initrd.availableKernelModules = [
			"xhci_pci"
			"ahci"
			"nvme"
			"usb_storage"
			"sd_mod"
		];

		loader = {
			efi = {
				canTouchEfiVariables = true;
				efiSysMountPoint = "/boot";
			};
			grub = lib.mkForce {
				enable = true;
				device = "nodev";
				configurationLimit = 4;
				efiSupport = true;
			};
		};
	};

	# TODO: Replace with actual disk UUIDs from blkid
	fileSystems."/" = {
		device = "/dev/disk/by-uuid/REPLACE-ME";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/REPLACE-ME";
		fsType = "vfat";
	};

	swapDevices = [ ];

	networking.useDHCP = lib.mkDefault true;
	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

	hardware = {
		cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
