# Generated by 'nixos-generate-config' on the est machine.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    kernelParams = [ "i915.force_probe=a7a0" ];

    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];

    loader = {
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot";
      };
      grub = lib.mkForce {
        enable = true;
        device = "nodev";
        configurationLimit = 4;
        efiSupport = true;
      };
    };
  };

  services.fstrim.enable = true;

  fileSystems = {
    "/home/sona/omnium-gatherum" = {
      device = "fw13:/home/sona/Git/omnium-gatherum";
      fsType = "nfs4";
      options = [
        "x-systemd.automount"
        "x-systemd.idle-timeout=600"
        "x-systemd.device-timeout=5"
        "noauto"
        "soft"
        "timeo=14"
        "retrans=2"
      ];
    };

    "/" = {
      device = "/dev/disk/by-uuid/d0f0b87a-a4b6-4d45-97fd-8499324ed618";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A45A-AA17";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
